## muutama mukava asetus

## f3:lla copy moodiin, samoin hiirellä ja page upilla
bind-key -n F3 copy-mode
set -g mouse on

unbind-key -n PageUp
unbind-key -n PageDown

bind-key -n C-PageUp copy-mode -eu
bind-key -n C-PageDown send-keys PageDown

## history bufferia myös hyvä vähän kasvattaa (orig. 2000)
set-option -g history-limit 200000
